"""add auth table

Revision ID: cb8062885e6c
Revises: 
Create Date: 2026-03-30 22:19:48.196697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8062885e6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('Auth_userid', sa.String(length=30), nullable=False),
    sa.Column('Auth_password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Auth_userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    # ### end Alembic commands ###
