"""sync

Revision ID: f078466f8e2e
Revises: 
Create Date: 2026-04-24 12:26:35.215618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f078466f8e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.Column('tags_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tags_id'),
    sa.UniqueConstraint('tags_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('icon_path', sa.String(), nullable=True),
    sa.Column('header_path', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_app', sa.String(), nullable=True),
    sa.Column('reply_to_post_id', sa.Integer(), nullable=True),
    sa.Column('quote_of_post_id', sa.Integer(), nullable=True),
    sa.Column('repost_of_post_id', sa.Integer(), nullable=True),
    sa.Column('thread_root_post_id', sa.Integer(), nullable=True),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quote_of_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['reply_to_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['repost_of_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['thread_root_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('content_hash')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_thread_root_post_id'), ['thread_root_post_id'], unique=False)

    op.create_table('profile_update',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('icon_path', sa.String(), nullable=True),
    sa.Column('header_path', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_table('post_bookmark',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('post_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.tags_id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tags_id')
    )
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_tags_tags_id'), ['tags_id'], unique=False)

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_tags_tags_id'))

    op.drop_table('post_tags')
    op.drop_table('post_images')
    op.drop_table('post_bookmark')
    op.drop_table('profile_update')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_thread_root_post_id'))

    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
